baseURL = 'https://pawntoh.com/'
locale = 'en-us'
title = '勤嬉軒'
theme = "PaperMod"
disqusShortname = "qin-xi-xuan"

[menu]
  [[menu.main]]
    name = "TRPG"
    url = "/categories/trpg/"
    weight = 10
  [[menu.main]]
    name = "輝金世界"
    url = "/categories/Aurence/"
    weight = 20
  [[menu.main]]
    name = "桌遊心得"
    url = "/categories/boardgames/"
    weight = 30
  [[menu.main]]
    name = "閱讀心得"
    url = "/categories/boardgames/"
    weight = 40
  [[menu.main]]
    name = "電玩分享"
    url = "/categories/boardgames/"
    weight = 50
  [[menu.main]]
    name = "影視心得"
    url = "/categories/boardgames/"
    weight = 30

[params]
  comments = true
  description = "勤嬉軒——TRPG翻譯、原創世界觀輝金世界、桌遊、電玩和影視心得分享"