baseURL = 'https://qinxixuan.s8765301480.workers.dev/'
locale = 'en-us'
title = '勤嬉軒'
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "TRPG"
    url = "/categories/trpg/"
    weight = 10
  [[menu.main]]
    name = "輝金世界"
    url = "/categories/Aurence/"
    weight = 20
  [[menu.main]]
    name = "桌遊心得"
    url = "/categories/boardgames/"
    weight = 30